using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Agibuild.Fulora.Bridge.Generator;

/// <summary>
/// Emits a typed TypeScript client module (bridge.client.ts) from the Bridge Contract IR.
/// Each [JsExport] service becomes an exported proxy object with typed method wrappers.
/// </summary>
internal static class TypeScriptClientEmitter
{
    public static string EmitClient(BridgeContractModel ir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by Agibuild.Fulora.Bridge.Generator");
        sb.AppendLine("// Do not edit manually.");
        sb.AppendLine();

        var exports = ir.Services
            .Where(s => s.Direction == BridgeDirection.Export)
            .ToList();

        if (exports.Count == 0)
            return sb.ToString();

        EmitTypeImports(sb, ir.Dtos);
        sb.AppendLine("const rpc = () => window.agWebView.rpc;");
        sb.AppendLine();

        foreach (var service in exports)
        {
            EmitServiceProxy(sb, service);
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void EmitTypeImports(StringBuilder sb, System.Collections.Immutable.ImmutableArray<BridgeDtoModel> dtos)
    {
        if (dtos.Length == 0) return;

        var names = dtos.Select(d => d.Name).OrderBy(n => n);
        sb.AppendLine($"import type {{ {string.Join(", ", names)} }} from './bridge.d';");
        sb.AppendLine();
    }

    private static void EmitServiceProxy(StringBuilder sb, BridgeInterfaceModel service)
    {
        var varName = ModelExtractor.ToCamelCase(service.ServiceName);
        sb.AppendLine($"export const {varName} = {{");

        for (int i = 0; i < service.Methods.Length; i++)
        {
            var method = service.Methods[i];
            EmitMethodProxy(sb, method);
            if (i < service.Methods.Length - 1 || service.Events.Length > 0)
                sb.AppendLine();
        }

        foreach (var evt in service.Events)
        {
            sb.AppendLine($"  get {evt.CamelCaseName}() {{ return window.agWebView.bridge.{varName}.{evt.CamelCaseName}; }},");
        }

        sb.AppendLine("};");
    }

    private static void EmitMethodProxy(StringBuilder sb, BridgeMethodModel method)
    {
        var regularParams = method.Parameters.Where(p => !p.IsCancellationToken).ToList();
        var hasCancellation = method.HasCancellationToken;

        var tsParamParts = regularParams.Select(p =>
        {
            var tsType = TypeScriptEmitter.TypeRefToTypeScript(p.TypeRef);
            var optional = p.IsNullable || p.HasDefaultValue ? "?" : "";
            return $"{p.CamelCaseName}{optional}: {tsType}";
        }).ToList();

        if (hasCancellation)
            tsParamParts.Add("options?: { signal?: AbortSignal }");

        var tsParams = string.Join(", ", tsParamParts);

        string tsReturn;
        if (method.IsAsyncEnumerable)
        {
            var innerTs = method.AsyncEnumerableInnerTypeRef is null
                ? "unknown"
                : TypeScriptEmitter.TypeRefToTypeScript(method.AsyncEnumerableInnerTypeRef);
            tsReturn = $"AsyncIterable<{innerTs}>";
        }
        else
        {
            tsReturn = method.HasReturnValue
                ? $"Promise<{GetReturnType(method)}>"
                : "Promise<void>";
        }

        sb.AppendLine($"  {method.CamelCaseName}({tsParams}): {tsReturn} {{");

        if (method.IsAsyncEnumerable)
        {
            EmitAsyncEnumerableBody(sb, method, regularParams);
        }
        else
        {
            EmitInvokeBody(sb, method, regularParams, hasCancellation);
        }

        sb.AppendLine("  },");
    }

    private static void EmitInvokeBody(
        StringBuilder sb,
        BridgeMethodModel method,
        List<BridgeParameterModel> regularParams,
        bool hasCancellation)
    {
        var paramsArg = regularParams.Count > 0
            ? "{ " + string.Join(", ", regularParams.Select(p => p.CamelCaseName)) + " }"
            : "undefined";

        if (hasCancellation)
        {
            sb.AppendLine($"    return rpc().invoke('{method.RpcMethodName}', {paramsArg}, options && options.signal) as {GetReturnCast(method)};");
        }
        else
        {
            sb.AppendLine($"    return rpc().invoke('{method.RpcMethodName}', {paramsArg}) as {GetReturnCast(method)};");
        }
    }

    private static void EmitAsyncEnumerableBody(
        StringBuilder sb,
        BridgeMethodModel method,
        List<BridgeParameterModel> regularParams)
    {
        var paramsArg = regularParams.Count > 0
            ? "{ " + string.Join(", ", regularParams.Select(p => p.CamelCaseName)) + " }"
            : "undefined";

        sb.AppendLine($"    return rpc()._createAsyncIterable('{method.RpcMethodName}', {paramsArg});");
    }

    private static string GetReturnCast(BridgeMethodModel method)
    {
        if (method.HasReturnValue)
            return $"Promise<{GetReturnType(method)}>";
        return "Promise<void>";
    }

    private static string GetReturnType(BridgeMethodModel method)
        => method.InnerReturnTypeRef is null
            ? "void"
            : TypeScriptEmitter.TypeRefToTypeScript(method.InnerReturnTypeRef);
}
