using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Agibuild.Avalonia.WebView.Bridge.Generator;

/// <summary>
/// Emits the <c>*BridgeRegistration</c> class for <see cref="BridgeDirection.Export"/> interfaces.
/// Each method gets a direct RPC handler — no reflection at runtime.
/// </summary>
internal static class BridgeHostEmitter
{
    public static string Emit(BridgeInterfaceModel model)
    {
        var sb = new StringBuilder();
        var className = $"{model.ServiceName}BridgeRegistration";
        var ns = model.Namespace;

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable IL2026 // Suppress trim analysis warnings for JSON deserialization in generated bridge code");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Agibuild.Avalonia.WebView;");
        sb.AppendLine();

        // Assembly attribute
        sb.AppendLine($"[assembly: global::Agibuild.Avalonia.WebView.BridgeRegistration(typeof({model.InterfaceFullName}), typeof({GetFullClassName(ns, className)}))]");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

        sb.AppendLine($"{indent}[global::System.CodeDom.Compiler.GeneratedCode(\"Agibuild.WebView.BridgeGenerator\", \"1.0.0\")]");
        sb.AppendLine($"{indent}internal sealed class {className} : global::Agibuild.Avalonia.WebView.IBridgeServiceRegistration<{model.InterfaceFullName}>");
        sb.AppendLine($"{indent}{{");

        // ServiceName
        sb.AppendLine($"{indent}    public string ServiceName => \"{model.ServiceName}\";");
        sb.AppendLine();

        // MethodNames
        sb.Append($"{indent}    public IReadOnlyList<string> MethodNames => new string[] {{ ");
        for (int i = 0; i < model.Methods.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append($"\"{model.Methods[i].RpcMethodName}\"");
        }
        sb.AppendLine(" };");
        sb.AppendLine();

        // RegisterHandlers
        EmitRegisterHandlers(sb, model, indent);
        sb.AppendLine();

        // UnregisterHandlers
        EmitUnregisterHandlers(sb, model, indent);
        sb.AppendLine();

        // GetJsStub
        EmitGetJsStub(sb, model, indent);

        sb.AppendLine($"{indent}}}");

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void EmitRegisterHandlers(StringBuilder sb, BridgeInterfaceModel model, string indent)
    {
        sb.AppendLine($"{indent}    public void RegisterHandlers(global::Agibuild.Avalonia.WebView.IWebViewRpcService rpc, {model.InterfaceFullName} impl)");
        sb.AppendLine($"{indent}    {{");

        foreach (var method in model.Methods)
        {
            sb.AppendLine($"{indent}        rpc.Handle(\"{method.RpcMethodName}\", async (global::System.Text.Json.JsonElement? __args) =>");
            sb.AppendLine($"{indent}        {{");

            // Deserialize parameters
            foreach (var param in method.Parameters)
            {
                var camel = param.CamelCaseName;
                var type = param.TypeFullName;

                if (param.IsNullable || param.HasDefaultValue)
                {
                    var defaultVal = param.HasDefaultValue ? param.DefaultValueLiteral ?? "default" : "default";
                    sb.AppendLine($"{indent}            {type} __{camel} = {defaultVal};");
                    sb.AppendLine($"{indent}            if (__args.HasValue && __args.Value.TryGetProperty(\"{camel}\", out var __{camel}Prop) && __{camel}Prop.ValueKind != global::System.Text.Json.JsonValueKind.Null)");
                    sb.AppendLine($"{indent}                __{camel} = __{camel}Prop.Deserialize<{type}>(BridgeGeneratedJsonOptions.Instance);");
                }
                else
                {
                    sb.AppendLine($"{indent}            var __{camel}Prop = __args.HasValue && __args.Value.TryGetProperty(\"{camel}\", out var __p_{camel}) ? __p_{camel} : default;");
                    sb.AppendLine($"{indent}            var __{camel} = __{camel}Prop.Deserialize<{type}>(BridgeGeneratedJsonOptions.Instance)!;");
                }
            }

            // Call implementation
            var paramList = string.Join(", ", method.Parameters.Select(p => $"__{p.CamelCaseName}"));

            if (method.IsAsync && method.HasReturnValue)
            {
                sb.AppendLine($"{indent}            var __result = await impl.{method.Name}({paramList}).ConfigureAwait(false);");
                sb.AppendLine($"{indent}            return (object?)__result;");
            }
            else if (method.IsAsync)
            {
                sb.AppendLine($"{indent}            await impl.{method.Name}({paramList}).ConfigureAwait(false);");
                sb.AppendLine($"{indent}            return (object?)null;");
            }
            else if (method.HasReturnValue)
            {
                sb.AppendLine($"{indent}            var __result = impl.{method.Name}({paramList});");
                sb.AppendLine($"{indent}            return (object?)__result;");
            }
            else
            {
                sb.AppendLine($"{indent}            impl.{method.Name}({paramList});");
                sb.AppendLine($"{indent}            return (object?)null;");
            }

            sb.AppendLine($"{indent}        }});");
        }

        sb.AppendLine($"{indent}    }}");
    }

    private static void EmitUnregisterHandlers(StringBuilder sb, BridgeInterfaceModel model, string indent)
    {
        sb.AppendLine($"{indent}    public void UnregisterHandlers(global::Agibuild.Avalonia.WebView.IWebViewRpcService rpc)");
        sb.AppendLine($"{indent}    {{");

        foreach (var method in model.Methods)
        {
            sb.AppendLine($"{indent}        rpc.RemoveHandler(\"{method.RpcMethodName}\");");
        }

        sb.AppendLine($"{indent}    }}");
    }

    private static void EmitGetJsStub(StringBuilder sb, BridgeInterfaceModel model, string indent)
    {
        sb.AppendLine($"{indent}    public string GetJsStub() => @\"");
        sb.AppendLine($"{indent}(function() {{");
        sb.AppendLine($"{indent}    if (!window.agWebView) window.agWebView = {{}};");
        sb.AppendLine($"{indent}    if (!window.agWebView.bridge) window.agWebView.bridge = {{}};");
        sb.Append($"{indent}    window.agWebView.bridge.{model.ServiceName} = {{ ");

        var jsMethodParts = new List<string>();
        foreach (var m in model.Methods)
        {
            jsMethodParts.Add($"{m.CamelCaseName}: function(params) {{ return window.agWebView.rpc.invoke('{m.RpcMethodName}', params); }}");
        }
        sb.Append(string.Join(", ", jsMethodParts));

        sb.AppendLine(" };");
        sb.AppendLine($"{indent}}})();\";");
    }

    private static string GetFullClassName(string ns, string className)
    {
        return string.IsNullOrEmpty(ns) ? $"global::{className}" : $"global::{ns}.{className}";
    }
}
