using System.Text;

namespace Agibuild.Avalonia.WebView.Bridge.Generator;

/// <summary>
/// Emits a shared <c>BridgeGeneratedJsonOptions</c> static class with camelCase + case-insensitive JsonSerializerOptions.
/// Generated once per assembly containing bridge interfaces.
/// </summary>
internal static class JsonOptionsEmitter
{
    public static string Emit(string? ns)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

        sb.AppendLine($"{indent}[global::System.CodeDom.Compiler.GeneratedCode(\"Agibuild.WebView.BridgeGenerator\", \"1.0.0\")]");
        sb.AppendLine($"{indent}internal static class BridgeGeneratedJsonOptions");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    internal static readonly global::System.Text.Json.JsonSerializerOptions Instance = new()");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        PropertyNameCaseInsensitive = true,");
        sb.AppendLine($"{indent}        PropertyNamingPolicy = global::System.Text.Json.JsonNamingPolicy.CamelCase,");
        sb.AppendLine($"{indent}    }};");
        sb.AppendLine($"{indent}}}");

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}
